package parser

import "strings"

// TokenType 词法单元类型
type TokenType int

const (
	// 特殊标记
	TOKEN_EOF TokenType = iota
	TOKEN_ILLEGAL

	// 字面量
	TOKEN_IDENTIFIER
	TOKEN_STRING
	TOKEN_NUMBER
	TOKEN_FLOAT

	// 关键字
	TOKEN_CREATE
	TOKEN_DROP
	TOKEN_ALTER
	TOKEN_TABLE
	TOKEN_DATABASE
	TOKEN_INSERT
	TOKEN_UPDATE
	TOKEN_DELETE
	TOKEN_SELECT
	TOKEN_WHERE
	TOKEN_FROM
	TOKEN_SET
	TOKEN_VALUES
	TOKEN_INTO
	TOKEN_ADD
	TOKEN_MODIFY
	TOKEN_COLUMN
	TOKEN_PRIMARY
	TOKEN_KEY
	TOKEN_FOREIGN
	TOKEN_NOT
	TOKEN_NULL
	TOKEN_UNIQUE
	TOKEN_DEFAULT
	TOKEN_IDENTITY
	TOKEN_CHECK
	TOKEN_INT
	TOKEN_INTEGER
	TOKEN_BOOL
	TOKEN_BOOLEAN
	TOKEN_DOUBLE
	TOKEN_VARCHAR
	TOKEN_DATETIME
	TOKEN_AND
	TOKEN_OR
	TOKEN_TRUE
	TOKEN_FALSE
	TOKEN_USE
	TOKEN_SHOW
	TOKEN_INDEX
	TOKEN_ON
	TOKEN_USER
	TOKEN_PASSWORD
	TOKEN_GRANT
	TOKEN_REVOKE
	TOKEN_BACKUP
	TOKEN_RESTORE
	TOKEN_TO
	TOKEN_BEGIN
	TOKEN_COMMIT
	TOKEN_ROLLBACK
	TOKEN_DESC
	TOKEN_ASC
	TOKEN_DATABASES
	TOKEN_TABLES

	// 操作符与分隔符
	TOKEN_LPAREN    // (
	TOKEN_RPAREN    // )
	TOKEN_COMMA     // ,
	TOKEN_SEMICOLON // ;
	TOKEN_STAR      // *
	TOKEN_EQ        // =
	TOKEN_LT        // <
	TOKEN_GT        // >
	TOKEN_LE        // <=
	TOKEN_GE        // >=
	TOKEN_NE        // <>
	TOKEN_DOT       // .
)

// Token 词法单元
type Token struct {
	Type    TokenType
	Literal string
}

var keywords = map[string]TokenType{
	"CREATE":   TOKEN_CREATE,
	"DROP":     TOKEN_DROP,
	"ALTER":    TOKEN_ALTER,
	"TABLE":    TOKEN_TABLE,
	"DATABASE": TOKEN_DATABASE,
	"INSERT":   TOKEN_INSERT,
	"UPDATE":   TOKEN_UPDATE,
	"DELETE":   TOKEN_DELETE,
	"SELECT":   TOKEN_SELECT,
	"WHERE":    TOKEN_WHERE,
	"FROM":     TOKEN_FROM,
	"SET":      TOKEN_SET,
	"VALUES":   TOKEN_VALUES,
	"INTO":     TOKEN_INTO,
	"ADD":      TOKEN_ADD,
	"MODIFY":   TOKEN_MODIFY,
	"COLUMN":   TOKEN_COLUMN,
	"PRIMARY":  TOKEN_PRIMARY,
	"KEY":      TOKEN_KEY,
	"FOREIGN":  TOKEN_FOREIGN,
	"NOT":      TOKEN_NOT,
	"NULL":     TOKEN_NULL,
	"UNIQUE":   TOKEN_UNIQUE,
	"DEFAULT":  TOKEN_DEFAULT,
	"IDENTITY": TOKEN_IDENTITY,
	"CHECK":    TOKEN_CHECK,
	"INT":      TOKEN_INT,
	"INTEGER":  TOKEN_INTEGER,
	"BOOL":     TOKEN_BOOL,
	"BOOLEAN":  TOKEN_BOOLEAN,
	"DOUBLE":   TOKEN_DOUBLE,
	"VARCHAR":  TOKEN_VARCHAR,
	"DATETIME": TOKEN_DATETIME,
	"AND":      TOKEN_AND,
	"OR":       TOKEN_OR,
	"TRUE":     TOKEN_TRUE,
	"FALSE":    TOKEN_FALSE,
	"USE":      TOKEN_USE,
	"SHOW":     TOKEN_SHOW,
	"INDEX":    TOKEN_INDEX,
	"ON":       TOKEN_ON,
	"USER":     TOKEN_USER,
	"PASSWORD": TOKEN_PASSWORD,
	"GRANT":    TOKEN_GRANT,
	"REVOKE":   TOKEN_REVOKE,
	"BACKUP":   TOKEN_BACKUP,
	"RESTORE":  TOKEN_RESTORE,
	"TO":       TOKEN_TO,
	"BEGIN":    TOKEN_BEGIN,
	"COMMIT":   TOKEN_COMMIT,
	"ROLLBACK": TOKEN_ROLLBACK,
	"DESC":      TOKEN_DESC,
	"ASC":       TOKEN_ASC,
	"DATABASES": TOKEN_DATABASES,
	"TABLES":    TOKEN_TABLES,
}

// LookupIdent 查找关键字
func LookupIdent(ident string) TokenType {
	if tok, ok := keywords[strings.ToUpper(ident)]; ok {
		return tok
	}
	return TOKEN_IDENTIFIER
}

func (t TokenType) String() string {
	switch t {
	case TOKEN_EOF:
		return "EOF"
	case TOKEN_IDENTIFIER:
		return "IDENT"
	case TOKEN_STRING:
		return "STRING"
	case TOKEN_NUMBER:
		return "NUMBER"
	case TOKEN_FLOAT:
		return "FLOAT"
	default:
		return "TOKEN"
	}
}
